In [ ]:
#AMB2296

In [ ]:
import pandas as pd
production= pd.Series(
[30,60,45,25],
index=["wheat","rice","maize","barley"])
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crop name(label)
print(production["rice"])
print(production.loc["rice"])
print(production["maize"])

60
60
45

In [ ]:
print(production.iloc[0])

30

In [ ]:
print(production.sum())
print(production.mean())
print(production.median())
print(production.max())
print(production.min())
print(production.idxmax())
print(production.idxmax(),"is having maximum production")
print(production.idxmin(),"is having minimum production")

160
40.0
37.5
60
25
rice
rice is having maximum production
barley is having minimum production

In [ ]:
increased_production=production*1.10
print(increased_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
high_production=production[production>40]
print(high_production)

rice     60
maize    45
dtype: int64

In [ ]:
df=pd.DataFrame({
    "name":["ram","shyam","hari"],
    "age":["15","25","20"],
    "city":["kathmandu","bhaktapur","lalitpur"]
},index=["a","b","c"])
print(df)
print()
print(df.loc["a"])

    name age       city
a    ram  15  kathmandu
b  shyam  25  bhaktapur
c   hari  20   lalitpur

name          ram
age            15
city    kathmandu
Name: a, dtype: object

In [ ]:
print(df.loc[["a","c"],["name","city"]])

   name       city
a   ram  kathmandu
c  hari   lalitpur

In [ ]:
print(df.loc["a":"c"])

    name age       city
a    ram  15  kathmandu
b  shyam  25  bhaktapur
c   hari  20   lalitpur

In [ ]:
print(df.loc[df["age"].astype(int) > 15,["name","age"]])

    name age
b  shyam  25
c   hari  20

In [ ]:
print(df.iloc[[0,2],[1,2]])

  age       city
a  15  kathmandu
c  20   lalitpur

In [ ]:
print(df.iloc[[0:2][0:2]])

SyntaxError: invalid syntax (ipython-input-2788662417.py, line 1)

In [ ]:
import pandas as pd
data={
    "Farm":["Farm A","Farm B","Farm C","farm D"],
    "Crop":["Wheat","Rice","wheat","maize"],
    "area_hectare":[10,15,8,12],
    "production_tons":[30,60,24,36],
}
df=pd.DataFrame(data)
print(df)

     Farm   Crop  area_hectare  production_tons
0  Farm A  Wheat            10               30
1  Farm B   Rice            15               60
2  Farm C  wheat             8               24
3  farm D  maize            12               36

In [ ]:
df.tail(2)
df.head(2)

     Farm   Crop  area_hectare  production_tons
0  Farm A  Wheat            10               30
1  Farm B   Rice            15               60

In [ ]:
df.describe()

       area_hectare  production_tons
count      4.000000         4.000000
mean      11.250000        37.500000
std        2.986079        15.779734
min        8.000000        24.000000
25%        9.500000        28.500000
50%       11.000000        33.000000
75%       12.750000        42.000000
max       15.000000        60.000000

In [ ]:
df["yield_per_hectare"]=df["production_tons"]/df["area_hectare"]
print(df)

     Farm   Crop  area_hectare  production_tons  yield_per_hectare
0  Farm A  Wheat            10               30                3.0
1  Farm B   Rice            15               60                4.0
2  Farm C  wheat             8               24                3.0
3  farm D  maize            12               36                3.0

In [ ]:
df.iloc[[1,3]]
print(df)

     Farm   Crop  area_hectare  production_tons  yield_per_hectare
0  Farm A  Wheat            10               30                3.0
1  Farm B   Rice            15               60                4.0
2  Farm C  wheat             8               24                3.0
3  farm D  maize            12               36                3.0

In [ ]:
print(df["crops"]=="wheat")
print()
wheat_farms=df[df["crops"]=="wheat"]
print(wheat_farms)

KeyError: 'crops'

In [ ]:
sorted_df=df.sort_values(by="area_hectare",ascending=False)
print(sorted_df)

     Farm   Crop  area_hectare  production_tons  yield_per_hectare
1  Farm B   Rice            15               60                4.0
3  farm D  maize            12               36                3.0
0  Farm A  Wheat            10               30                3.0
2  Farm C  wheat             8               24                3.0

In [ ]:
avg_yield=df.groupyby("crops")["yield_per_hectare"].sum()
print(avg_yield)

AttributeError: 'DataFrame' object has no attribute 'groupyby'